server:
  port: 80
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.232.217:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&requireSSL=false
    username: root
    password: liu123
    # redis 配置
  redis:
    # 地址
    host: '47.100.232.217'
    # 端口，默认为6379
    port: 6379
    # 密码，没有不填
    password: 'liu123'
    # 连接超时时间
    timeout: 3600s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

mybatis:
  mapper-locations: classpath:**/*.xml
  type-aliases-package: com.atguigu.springcloud.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
